name: Publish Docker
on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    environment:
      name: Docker-latest
      url: https://github.com/createstructure/core-createstructure/packages/856124
    steps:
    - uses: actions/checkout@v2
    - name: Install docker
      run: |
        sudo apt install docker.io -y
    - name: Build for any platform
      run: |
        docker buildx build --platform linux/amd64,linux/arm64 .
        
